### ISSUE TITLE
Add helper to test that the user submitted a ggplot2

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/ggcheck#20]
``` r
library(ggplot2)
library(ggcheck)
```

When a user misses a `+` or has another small mistake in the snytax, the last value from running their code can end up being a ggplot2 component (layer, aesthetic, etc) but not the plot we expect.

``` r
.result <- local({
  ggplot(mpg) +
    aes(x = hwy, y = cyl) + 
    geom_point() 
    geom_smooth()
})
```

If you try to use `ggcheck` functions right away, we run into an error.

``` r
uses_data(.result, mpg)
#> Error in UseMethod("get_data"): no applicable method for 'get_data' applied to an object of class "c('LayerInstance', 'Layer', 'ggproto', 'gg')"
```

We need a helper function to test that the output is a ggplot2 plot and to give useful feedback — did you forget a `+`, etc. — without giving away the answer via code checking.

``` r
inherits(.result, "ggplot")
#> [1] FALSE
```

<sup>Created on 2021-11-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rossellhayes** [comment]
Would this be a new function, e.g. `is_ggplot()`, that would run at the beginning of every `*-check` chunk, or a test that's incorporated at the beginning of each `uses_*()` function?

**Comment by gadenbuie** [comment]
Probably both

**Comment by gadenbuie** [comment]
To clarify: probably both in the sense that we should have a public function to test that we're working with a ggplot2 plot. And internally we'll want to add more checks inside each of the ggcheck test functions that ensure we're working with the right object types.

More broadly, we'll also probably want to bring in gradethis and provide some basic feedback, e.g. `fail_if_not_ggplot()`, where we can be a little more targeted to common ggplot2 problems with our feedback.
