### ISSUE TITLE
Add pattern to check for presence of label in plot

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/ggcheck#24]
It might be useful to update the `uses_label()` API to make it easier to test for the presence of ~user defined~ labels. Using the example from #22, unnamed arguments would simply be a test for presence of the label, not specifically comparing a value:

```r
library(ggcheck)
library(ggplot2)

p <- ggplot(mtcars, aes(x = wt, y = mpg, color = cyl)) +
  geom_point() +
  labs(x = "weight", y = "MPG", color = NULL)

get_labels(p)
#> $x
#> [1] "weight"
#> 
#> $y
#> [1] "MPG"
#> 
#> $colour
#> NULL
```

```r
uses_labels(p, "x")
#> [1] TRUE

uses_labels(p, x = "weight")
#> [1] TRUE

uses_labels(p, "fill")
#> [1] FALSE

uses_labels(p, "fill", "shape")
#> [1] FALSE FALSE
```

cc @brendanhcullen

**Comment by gadenbuie** [comment]
Or possibly leaving the label variables unquoted?

```r
uses_labels(p, x)
#> [1] TRUE

uses_labels(p, x = "weight")
#> [1] TRUE

uses_labels(p, fill)
#> [1] FALSE

uses_labels(p, fill, shape)
#> [1] FALSE FALSE
```

**Comment by rossellhayes** [comment]
@brendanhcullen @gadenbuie
I agree with this, but I'm not sure the best way to do it in practice. The `labels` of a `ggplot` object don't distinguish between user-specified labels and automatic labels:
``` r
library(ggcheck)
library(ggplot2)

p <- ggplot(mtcars, aes(x = wt, y = mpg, color = cyl)) +
  geom_point()

get_labels(p)
#> $x
#> [1] "wt"
#> 
#> $y
#> [1] "mpg"
#> 
#> $colour
#> [1] "cyl"
```

<sup>Created on 2021-11-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Is the solution to compare the labels to the input to `aes()` and check that they don't match?

**Comment by rossellhayes** [comment]
All geoms have a label unless the user specifically sets it to `NULL`. `uses_label(p, "fill")` would the equivalent of `uses_geom(p, "fill") & !uses_label(p, fill = NULL)`. In other words, it would pass for any geom with a default label or with a user-defined label, unless the user-defined label is `NULL`. I did originally build `uses_label()` to work that way, but it didn't seem useful to me. Is there a place where that functionality would be helpful?

**Comment by gadenbuie** [comment]
But not all labels have aesthetics

```r
uses_aesthetics(p, "fill")
#> [1] FALSE
uses_aesthetics(p, "title")
#> [1] FALSE
uses_aesthetics(p + ggtitle("title"), "title")
#> [1] FALSE
```

And `get_labels(p)` shows that we can know that a label was unspecified — with the caveat that labels derived from aesthetics may be masked (as you point out) by their default label values.

```r
get_labels(p)
#> $x
#> [1] "weight"
#> 
#> $y
#> [1] "MPG"
#> 
#> $colour
#> NULL
```

```r
"title" %in% names(get_labels(p))
#> [1] FALSE
"title" %in% names(get_labels(p + ggtitle("title")))
#> [1] TRUE
uses_labels(p, title = NULL)
#> [1] TRUE
```

So what we want is something like the last call, but without the value, e.g.

```r
uses_labels(p, "title")
#> [1] FALSE
```

**Comment by rossellhayes** [comment]
@gadenbuie Oh I follow now!, thank you for clearing that up for me! I hadn't thought about those labels `title` or `caption` that don't have an associated aesthetic. I'll work on implementing this!
