### ISSUE TITLE
Rethink functions that take `...`

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/ggcheck#25]
Having functions that take a list of aesthetics or labels in `...` is helpful interactively or when the number of items is small or well known. On the other hand, it's hard to programmatically construct calls to functions like `uses_labels()` when one is working with an abstract (or unknown) number of labels/aesthetics/etc.

``` r
library(ggcheck)
library(ggplot2)

p <- ggplot(mtcars, aes(x = wt, y = mpg, color = cyl)) +
  geom_point() +
  labs(x = "weight", y = "MPG", color = NULL)
```

The following isn’t possible currently since we need arguments to `...`, but we could allow the first argument to be a list, in which case it becomes the starting structure for the internal `args` list.

``` r
uses_labels(p, list(x = "weight", y = "MPG"))
#> Error: All inputs to `...` must be character vectors of length 1 or `NULL`.
```

Another option is to use rlang’s dynamic dots via `rlang::list2()` to enable splicing.

``` r
uses_labels(p, !!!list(x = "weight", y = "MPG"))
#> Error in !list(x = "weight", y = "MPG"): invalid argument type
```

Still, the current version calls `all()` on all of the labels/aesthetics, but from a programmatic perspective it might be better to return a named vector.

``` r
uses_labels(p, x = "weight", y = "MPG")
#> [1] TRUE

# may be easier in the long term to return a named logical vector
uses_labels(p, x = "weight", y = "MPG")
#>    x    y
#> TRUE TRUE
```

**Comment by rossellhayes** [comment]
Agreed on all fronts. Could it cause any issues to implement both solutions for filling in the `...` programmatically, i.e. to support a `list` argument _and_ dynamic dots?

Outputting a vector instead of using `all()`will be a breaking change, so I'll make sure that we wrap `uses_labels()` in `all()` anywhere we currently use it.
